#!/usr/bin/env python3
"""Generate the 256→16 palette quantization table for Render.HC.

Inputs:
- A 256-entry RGB palette ("Quake's", or a stand-in)
- TempleOS's fixed 16-color DC palette (CGA-derived)

Output:
- HolyC source fragment containing `U8 _render_quant_table[256]`
  where entry N is the TempleOS color (0..15) closest in
  Euclidean RGB space to Quake palette entry N.

Usage:
    scripts/gen-palette.py            # writes src/RenderPalette.HH
    scripts/gen-palette.py --stdout   # prints to stdout

The Quake palette is normally in `id1/gfx/palette.lmp` (768 bytes
= 256 RGB triplets). We don't ship that asset, so this script
defaults to a representative synthetic palette covering the same
color space (RGB cube + grayscale ramp). When palette.lmp is
available, replace `_quake_palette()` with a `Path(...).read_bytes()`
loader. The table format and Render.HC consumption are
unchanged.
"""
from __future__ import annotations

import sys
from pathlib import Path

# TempleOS DC's 16-color CGA palette. RGB approximations from
# WinAPI / IBM standard. Indices match `gr.dc->color = N` values.
TEMPLEOS_PALETTE = [
    (0x00, 0x00, 0x00),   # 0  BLACK
    (0x00, 0x00, 0xAA),   # 1  BLUE
    (0x00, 0xAA, 0x00),   # 2  GREEN
    (0x00, 0xAA, 0xAA),   # 3  CYAN
    (0xAA, 0x00, 0x00),   # 4  RED
    (0xAA, 0x00, 0xAA),   # 5  PURPLE
    (0xAA, 0x55, 0x00),   # 6  BROWN
    (0xAA, 0xAA, 0xAA),   # 7  LTGRAY
    (0x55, 0x55, 0x55),   # 8  DKGRAY
    (0x55, 0x55, 0xFF),   # 9  LTBLUE
    (0x55, 0xFF, 0x55),   # 10 LTGREEN
    (0x55, 0xFF, 0xFF),   # 11 LTCYAN
    (0xFF, 0x55, 0x55),   # 12 LTRED
    (0xFF, 0x55, 0xFF),   # 13 LTPURPLE
    (0xFF, 0xFF, 0x55),   # 14 YELLOW
    (0xFF, 0xFF, 0xFF),   # 15 WHITE
]


def _quake_palette() -> list[tuple[int, int, int]]:
    """Return 256 RGB triplets standing in for gfx/palette.lmp.

    Layout chosen to roughly mirror Quake's actual palette ranges:
    a grayscale ramp at the start, then brown/tan + blue + green
    + red zones, ending with brights. When the real .lmp is
    available, swap this for a file-loader.
    """
    pal: list[tuple[int, int, int]] = []
    # 0..15: grayscale ramp 0→255
    for i in range(16):
        v = (i * 255) // 15
        pal.append((v, v, v))
    # 16..47: brown/tan ramp (brown family)
    for i in range(32):
        r = 80 + (i * 5)
        g = 50 + (i * 4)
        b = 30 + (i * 3)
        pal.append((min(r, 255), min(g, 255), min(b, 255)))
    # 48..79: blue ramp
    for i in range(32):
        pal.append((i * 4, i * 4, 80 + i * 5))
    # 80..111: green ramp
    for i in range(32):
        pal.append((i * 4, 80 + i * 5, i * 3))
    # 112..143: cyan-ish
    for i in range(32):
        pal.append((i * 3, 100 + i * 4, 120 + i * 4))
    # 144..175: red/fire
    for i in range(32):
        pal.append((150 + i * 3, 30 + i * 5, i * 4))
    # 176..207: yellow/gold
    for i in range(32):
        pal.append((200 + i, 180 + i * 2, i * 5))
    # 208..239: violet/purple
    for i in range(32):
        pal.append((100 + i * 4, i * 3, 100 + i * 4))
    # 240..255: brights — saturated primary spotlights
    spotlights = [
        (255, 0, 0), (0, 255, 0), (0, 0, 255),
        (255, 255, 0), (0, 255, 255), (255, 0, 255),
        (255, 128, 0), (128, 255, 0), (0, 255, 128),
        (0, 128, 255), (128, 0, 255), (255, 0, 128),
        (255, 255, 255), (192, 192, 192), (128, 128, 128),
        (64, 64, 64),
    ]
    pal.extend(spotlights)
    assert len(pal) == 256, f"palette length {len(pal)} != 256"
    # Clamp every channel to 0..255
    return [(min(255, max(0, r)),
             min(255, max(0, g)),
             min(255, max(0, b))) for (r, g, b) in pal]


def _nearest_index(rgb: tuple[int, int, int],
                   palette: list[tuple[int, int, int]]) -> int:
    """Return the index of the closest palette entry by Euclidean
    distance in RGB space."""
    r, g, b = rgb
    best_i = 0
    best_d = 1 << 30
    for i, (pr, pg, pb) in enumerate(palette):
        d = (r - pr) ** 2 + (g - pg) ** 2 + (b - pb) ** 2
        if d < best_d:
            best_d = d
            best_i = i
    return best_i


def _emit_table() -> str:
    quake = _quake_palette()
    table = [_nearest_index(c, TEMPLEOS_PALETTE) for c in quake]
    out: list[str] = []
    out.append("// AUTO-GENERATED by scripts/gen-palette.py — do not edit.")
    out.append("//")
    out.append("// Maps each Quake palette index (0..255) to the closest")
    out.append("// TempleOS DC color (0..15) in Euclidean RGB space. Built")
    out.append("// from a representative synthetic Quake palette;")
    out.append("// regenerate after dropping a real gfx/palette.lmp into")
    out.append("// the script.")
    out.append("")
    out.append("U8 _render_quant_table[256] = {")
    for row_start in range(0, 256, 16):
        row = table[row_start:row_start + 16]
        out.append("  " + ", ".join(f"{v:2d}" for v in row) + ",")
    out.append("};")
    out.append("")
    return "\n".join(out)


BEGIN_MARKER = "// === gen-palette.py BEGIN ==="
END_MARKER = "// === gen-palette.py END ==="


def _splice_into(target: Path, body: str) -> None:
    """Replace the BEGIN..END block inside `target` with `body`.

    Errors loudly if the markers aren't both present — we don't
    want to silently drop the table or duplicate it.
    """
    text = target.read_text()
    if BEGIN_MARKER not in text or END_MARKER not in text:
        raise SystemExit(
            f"error: {target} is missing BEGIN/END markers — "
            f"add `{BEGIN_MARKER}` and `{END_MARKER}` lines around "
            f"the spot where the generated table should live")
    head, _, rest = text.partition(BEGIN_MARKER)
    _, _, tail = rest.partition(END_MARKER)
    new = head + BEGIN_MARKER + "\n" + body + END_MARKER + tail
    if new == text:
        print(f"{target}: no change")
    else:
        target.write_text(new)
        print(f"{target}: spliced {body.count(chr(10))} lines")


def main(argv: list[str]) -> int:
    body = _emit_table()
    if "--stdout" in argv:
        print(body)
        return 0
    repo = Path(__file__).resolve().parent.parent
    target = repo / "src" / "Render.HC"
    _splice_into(target, body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
